import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Statement } from "./statements";
import { formatNAD } from "./format";

// Same deterministic path as the payslip: jsPDF over figures computed in the app, not a
// document generated by the AI assistant. See src/lib/statements.ts for why.
export function buildStatementPDF(opts: {
  statement: Statement;
  tenantName: string;
  client: { name: string; address?: string | null; vat_number?: string | null; contact_person?: string | null };
}): jsPDF {
  const { statement: s, tenantName, client } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18).setFont("helvetica", "bold");
  doc.text(tenantName, 40, 32);
  doc.setFontSize(10).setFont("helvetica", "normal");
  doc.text("STATEMENT OF ACCOUNT", 40, 52);
  doc.text(`${s.start} — ${s.end}`, W - 40, 52, { align: "right" });

  doc.setTextColor(0, 0, 0);
  let y = 95;
  doc.setFont("helvetica", "bold").setFontSize(11);
  doc.text(client.name, 40, y);
  doc.setFont("helvetica", "normal").setFontSize(9);
  let sub = y + 14;
  if (client.contact_person) { doc.text(`Attn: ${client.contact_person}`, 40, sub); sub += 12; }
  if (client.address) { doc.text(client.address.replace(/\n/g, ", "), 40, sub, { maxWidth: W / 2 }); sub += 12; }
  if (client.vat_number) { doc.text(`VAT ${client.vat_number}`, 40, sub); sub += 12; }

  autoTable(doc, {
    startY: Math.max(sub + 10, 150),
    head: [["Date", "Reference", "Detail", "Debit", "Credit", "Balance"]],
    body: [
      ["", "", { content: "Opening balance", styles: { fontStyle: "bold" } }, "", "", { content: formatNAD(s.openingBalance), styles: { fontStyle: "bold" } }],
      ...s.lines.map((l) => [
        l.date,
        l.reference,
        l.kind === "invoice" ? "Invoice" : "Payment received",
        l.debit ? formatNAD(l.debit) : "",
        l.credit ? formatNAD(l.credit) : "",
        formatNAD(l.balance),
      ]),
      ["", "", { content: "Closing balance", styles: { fontStyle: "bold" } }, "", "", { content: formatNAD(s.closingBalance), styles: { fontStyle: "bold" } }],
    ],
    theme: "striped",
    headStyles: { fillColor: [15, 23, 42] },
    styles: { fontSize: 9 },
    columnStyles: { 3: { halign: "right" }, 4: { halign: "right" }, 5: { halign: "right" } },
  });

  // @ts-expect-error autotable adds this
  y = doc.lastAutoTable.finalY + 20;

  autoTable(doc, {
    startY: y,
    head: [["Current", "30 days", "60 days", "90+ days", "Total outstanding"]],
    body: [[
      formatNAD(s.aging.current), formatNAD(s.aging.d30),
      formatNAD(s.aging.d60), formatNAD(s.aging.d90),
      { content: formatNAD(s.agingTotal), styles: { fontStyle: "bold" } },
    ]],
    theme: "grid",
    headStyles: { fillColor: [120, 53, 15] },
    styles: { fontSize: 9, halign: "right" },
  });

  // @ts-expect-error autotable
  y = doc.lastAutoTable.finalY + 24;
  doc.setFontSize(8).setTextColor(90, 90, 90);
  doc.text(
    "Balances are computed from issued invoices and payments received. Draft and voided invoices are excluded. Aging is measured against each invoice's due date as at the closing date.",
    40, y, { maxWidth: W - 80 },
  );

  return doc;
}
