/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWizardRouteImport } from './routes/_app.wizard'
import { Route as AppSupervisorsRouteImport } from './routes/_app.supervisors'
import { Route as AppSitesRouteImport } from './routes/_app.sites'
import { Route as AppScheduleRouteImport } from './routes/_app.schedule'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppDisciplinaryRouteImport } from './routes/_app.disciplinary'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as AppAccountingRouteImport } from './routes/_app.accounting'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app.employees.index'
import { Route as AppOnboardingEmployeeIdRouteImport } from './routes/_app.onboarding.$employeeId'
import { Route as AppEmployeesNewRouteImport } from './routes/_app.employees.new'
import { Route as AppEmployeesImportRouteImport } from './routes/_app.employees.import'
import { Route as AppEmployeesEmployeeIdRouteImport } from './routes/_app.employees.$employeeId'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWizardRoute = AppWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorsRoute = AppSupervisorsRouteImport.update({
  id: '/supervisors',
  path: '/supervisors',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplinaryRoute = AppDisciplinaryRouteImport.update({
  id: '/disciplinary',
  path: '/disciplinary',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingEmployeeIdRoute = AppOnboardingEmployeeIdRouteImport.update({
  id: '/onboarding/$employeeId',
  path: '/onboarding/$employeeId',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesNewRoute = AppEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesImportRoute = AppEmployeesImportRouteImport.update({
  id: '/employees/import',
  path: '/employees/import',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesEmployeeIdRoute = AppEmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounting': typeof AppAccountingRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/approvals': typeof AppApprovalsRoute
  '/attendance': typeof AppAttendanceRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/disciplinary': typeof AppDisciplinaryRoute
  '/invoices': typeof AppInvoicesRoute
  '/payroll': typeof AppPayrollRoute
  '/schedule': typeof AppScheduleRoute
  '/sites': typeof AppSitesRoute
  '/supervisors': typeof AppSupervisorsRoute
  '/wizard': typeof AppWizardRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/employees/import': typeof AppEmployeesImportRoute
  '/employees/new': typeof AppEmployeesNewRoute
  '/onboarding/$employeeId': typeof AppOnboardingEmployeeIdRoute
  '/employees/': typeof AppEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounting': typeof AppAccountingRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/approvals': typeof AppApprovalsRoute
  '/attendance': typeof AppAttendanceRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/disciplinary': typeof AppDisciplinaryRoute
  '/invoices': typeof AppInvoicesRoute
  '/payroll': typeof AppPayrollRoute
  '/schedule': typeof AppScheduleRoute
  '/sites': typeof AppSitesRoute
  '/supervisors': typeof AppSupervisorsRoute
  '/wizard': typeof AppWizardRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/employees/import': typeof AppEmployeesImportRoute
  '/employees/new': typeof AppEmployeesNewRoute
  '/onboarding/$employeeId': typeof AppOnboardingEmployeeIdRoute
  '/employees': typeof AppEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/disciplinary': typeof AppDisciplinaryRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/sites': typeof AppSitesRoute
  '/_app/supervisors': typeof AppSupervisorsRoute
  '/_app/wizard': typeof AppWizardRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/_app/employees/import': typeof AppEmployeesImportRoute
  '/_app/employees/new': typeof AppEmployeesNewRoute
  '/_app/onboarding/$employeeId': typeof AppOnboardingEmployeeIdRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounting'
    | '/ai-assistant'
    | '/approvals'
    | '/attendance'
    | '/clients'
    | '/dashboard'
    | '/disciplinary'
    | '/invoices'
    | '/payroll'
    | '/schedule'
    | '/sites'
    | '/supervisors'
    | '/wizard'
    | '/admin/settings'
    | '/admin/users'
    | '/employees/$employeeId'
    | '/employees/import'
    | '/employees/new'
    | '/onboarding/$employeeId'
    | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounting'
    | '/ai-assistant'
    | '/approvals'
    | '/attendance'
    | '/clients'
    | '/dashboard'
    | '/disciplinary'
    | '/invoices'
    | '/payroll'
    | '/schedule'
    | '/sites'
    | '/supervisors'
    | '/wizard'
    | '/admin/settings'
    | '/admin/users'
    | '/employees/$employeeId'
    | '/employees/import'
    | '/employees/new'
    | '/onboarding/$employeeId'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/accounting'
    | '/_app/ai-assistant'
    | '/_app/approvals'
    | '/_app/attendance'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/disciplinary'
    | '/_app/invoices'
    | '/_app/payroll'
    | '/_app/schedule'
    | '/_app/sites'
    | '/_app/supervisors'
    | '/_app/wizard'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/employees/$employeeId'
    | '/_app/employees/import'
    | '/_app/employees/new'
    | '/_app/onboarding/$employeeId'
    | '/_app/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wizard': {
      id: '/_app/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof AppWizardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisors': {
      id: '/_app/supervisors'
      path: '/supervisors'
      fullPath: '/supervisors'
      preLoaderRoute: typeof AppSupervisorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sites': {
      id: '/_app/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disciplinary': {
      id: '/_app/disciplinary'
      path: '/disciplinary'
      fullPath: '/disciplinary'
      preLoaderRoute: typeof AppDisciplinaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/$employeeId': {
      id: '/_app/onboarding/$employeeId'
      path: '/onboarding/$employeeId'
      fullPath: '/onboarding/$employeeId'
      preLoaderRoute: typeof AppOnboardingEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/new': {
      id: '/_app/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AppEmployeesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/import': {
      id: '/_app/employees/import'
      path: '/employees/import'
      fullPath: '/employees/import'
      preLoaderRoute: typeof AppEmployeesImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$employeeId': {
      id: '/_app/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisciplinaryRoute: typeof AppDisciplinaryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSitesRoute: typeof AppSitesRoute
  AppSupervisorsRoute: typeof AppSupervisorsRoute
  AppWizardRoute: typeof AppWizardRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppEmployeesEmployeeIdRoute: typeof AppEmployeesEmployeeIdRoute
  AppEmployeesImportRoute: typeof AppEmployeesImportRoute
  AppEmployeesNewRoute: typeof AppEmployeesNewRoute
  AppOnboardingEmployeeIdRoute: typeof AppOnboardingEmployeeIdRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDisciplinaryRoute: AppDisciplinaryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSitesRoute: AppSitesRoute,
  AppSupervisorsRoute: AppSupervisorsRoute,
  AppWizardRoute: AppWizardRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppEmployeesEmployeeIdRoute: AppEmployeesEmployeeIdRoute,
  AppEmployeesImportRoute: AppEmployeesImportRoute,
  AppEmployeesNewRoute: AppEmployeesNewRoute,
  AppOnboardingEmployeeIdRoute: AppOnboardingEmployeeIdRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
